version: '2'
services:
    krakowskitarg-app:
        image: krakowskitarg
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://krakowskitarg-postgresql:5432/krakowskiTarg
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=krakowskitarg-elasticsearch:9300
        ports:
            - 8080:8080
    krakowskitarg-postgresql:
        extends:
            file: postgresql.yml
            service: krakowskitarg-postgresql
    krakowskitarg-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: krakowskitarg-elasticsearch
